export const DB_NAME = "Pansari";
export const DB_NAME1= "Unnati-Store";

export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_SUCESS = 'SIGNUP_SUCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCESS = 'LOGIN_SUCESS';

export const SPINNER_STATUS_REQUESTED = 'SPINNER_STATUS_REQUESTED';

export const GET_MEASURMENT_REQUESTED = 'GET_MEASURMENT_REQUESTED';
export const GET_MEASURMENT_SUCESS = 'GET_MEASURMENT_SUCESS';

export const ADD_MEASURMENT_REQUESTED = 'ADD_MEASURMENT_REQUESTED';
export const ADD_MEASURMENT_SUCESS = 'ADD_MEASURMENT_SUCESS';

export const GET_PRODUCT_CATEGORY_REQUESTED = 'GET_PRODUCT_CATEGORY_REQUESTED';
export const GET_PRODUCT_CATEGORY_SUCESS = 'GET_PRODUCT_CATEGORY_SUCESS';

export const GET_PRODUCT_COMPANY_REQUESTED = 'GET_PRODUCT_COMPANY_REQUESTED';
export const GET_PRODUCT_COMPANY_SUCESS = 'GET_PRODUCT_COMPANY_SUCESS';

export const ADD_PRODUCT_COMPANY_REQUESTED = 'ADD_PRODUCT_COMPANY_REQUESTED';
export const ADD_PRODUCT_COMPANY_SUCESS = 'ADD_PRODUCT_COMPANY_SUCESS';

export const ADD_PRODUCT_CATEGORY_REQUESTED = 'ADD_PRODUCT_CATEGORY_REQUESTED';
export const ADD_PRODUCT_CATEGORY_SUCESS = 'ADD_PRODUCT_CATEGORY_SUCESS';

export const GET_PRODUCTS_REQUESTED = 'GET_PRODUCTS_REQUESTED';
export const GET_PRODUCTS_SUCESS = 'GET_PRODUCTS_SUCESS';

export const ADD_PRODUCT_REQUESTED = 'ADD_PRODUCT_REQUESTED';
export const ADD_PRODUCT_SUCESS = 'ADD_PRODUCT_SUCESS';

export const GET_SHOPS_REQUESTED = 'GET_SHOPS_REQUESTED';
export const GET_SHOPS_SUCESS = 'GET_SHOPS_SUCESS';

export const ADD_SHOP_REQUESTED = 'ADD_SHOP_REQUESTED';
export const ADD_SHOP_SUCESS = 'ADD_SHOP_SUCESS';

export const GET_PURCHASE_ORDER_REQUESTED = 'GET_PURCHASE_ORDER_REQUESTED';
export const GET_PURCHASE_ORDER_SUCESS = 'GET_PURCHASE_ORDER_SUCESS';

export const SET_NOTIFICATION = 'SET_NOTIFICATION';
